export const SAVE_PERSON = 'ADD_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
export const ADD_PERSON_ATTRIBUTE = 'ADD_PERSON_ATTRIBUTE';
export const REMOVE_PERSON_ATTRIBUTE = 'REMOVE_PEOPLE_ATTRIBUTE';
export const CHANGE_PERSON_TYPE = 'CHANGE_PERSON_TYPE';
export const CHANGE_PERSON_DESCRIPTION = 'CHANGE_PERSON_DESCRIPTION';
export const SET_PERSON = 'SET_PERSON';
export const RESET_PERSON = 'RESET_PERSON';

export const SAVE_ACTION = 'ADD_ACTION';
export const DELETE_ACTION = 'DELETE_ACTION';
export const ADD_ACTION_ATTRIBUTE = 'ADD_ACTION_ATTRIBUTE';
export const REMOVE_ACTION_ATTRIBUTE = 'REMOVE_ACTION_ATTRIBUTE';
export const CHANGE_ACTION_TYPE = 'CHANGE_ACTION_TYPE';
export const CHANGE_ACTION_DESCRIPTION = 'CHANGE_ACTION_DESCRIPTION';
export const SET_ACTION = 'SET_ACTION';
export const RESET_ACTION = 'RESET_ACTION';

export const SAVE_THING = 'ADD_THING';
export const DELETE_THING = 'DELETE_THING';
export const ADD_THING_ATTRIBUTE = 'ADD_THING_ATTRIBUTE';
export const REMOVE_THING_ATTRIBUTE = 'REMOVE_THING_ATTRIBUTE';
export const CHANGE_THING_TYPE = 'CHANGE_THING_TYPE';
export const CHANGE_THING_DESCRIPTION = 'CHANGE_THING_DESCRIPTION';
export const SET_THING = 'SET_THING';
export const RESET_THING = 'RESET_THING';

export const ADD_RELATIONSHIP = 'ADD_RELATIONSHIP';
export const REMOVE_RELATIONSHIP = 'REMOVE_RELATIONSHIP';
