export const SAVE_PERSON = 'ADD_PERSON_ADMIN';
export const DELETE_PERSON = 'DELETE_PERSON_ADMIN';
export const ADD_PERSON_ATTRIBUTE = 'ADD_PERSON_ATTRIBUTE_ADMIN';
export const REMOVE_PERSON_ATTRIBUTE = 'REMOVE_PEOPLE_ATTRIBUTE_ADMIN';
export const CHANGE_PERSON_TYPE = 'CHANGE_PERSON_TYPE_ADMIN';
export const CHANGE_PERSON_DESCRIPTION = 'CHANGE_PERSON_DESCRIPTION_ADMIN';
export const SET_PERSON = 'SET_PERSON_ADMIN';
export const RESET_PERSON = 'RESET_PERSON_ADMIN';

export const SAVE_ACTION = 'ADD_ACTION_ADMIN';
export const DELETE_ACTION = 'DELETE_ACTION_ADMIN';
export const ADD_ACTION_ATTRIBUTE = 'ADD_ACTION_ATTRIBUTE_ADMIN';
export const REMOVE_ACTION_ATTRIBUTE = 'REMOVE_ACTION_ATTRIBUTE_ADMIN';
export const CHANGE_ACTION_TYPE = 'CHANGE_ACTION_TYPE_ADMIN';
export const CHANGE_ACTION_DESCRIPTION = 'CHANGE_ACTION_DESCRIPTION_ADMIN';
export const SET_ACTION = 'SET_ACTION_ADMIN';
export const RESET_ACTION = 'RESET_ACTION_ADMIN';

export const SAVE_THING = 'ADD_THING_ADMIN';
export const DELETE_THING = 'DELETE_THING_ADMIN';
export const ADD_THING_ATTRIBUTE = 'ADD_THING_ATTRIBUTE_ADMIN';
export const REMOVE_THING_ATTRIBUTE = 'REMOVE_THING_ATTRIBUTE_ADMIN';
export const CHANGE_THING_TYPE = 'CHANGE_THING_TYPE_ADMIN';
export const CHANGE_THING_DESCRIPTION = 'CHANGE_THING_DESCRIPTION_ADMIN';
export const SET_THING = 'SET_THING_ADMIN';
export const RESET_THING = 'RESET_THING_ADMIN';

export const ADD_RELATIONSHIP = 'ADD_RELATIONSHIP_ADMIN';
export const REMOVE_RELATIONSHIP = 'REMOVE_RELATIONSHIP_ADMIN';
